services:
  frontend-build:
    build:
      context: .

    container_name: frontend-build

    volumes:
      - .:/app
      - node_modules_frontend:/app/node_modules

    command: npm run build

volumes:
  node_modules_frontend:
