services:
  backend:
    build:
      context: .

    container_name: nest-backend

    expose:
      - '3000'

    env_file:
      - .env

    networks:
      - backend-network

networks:
  backend-network:
    external: true
    name: projeto-aprendizado-network
